const baseUrl = {
    url: 'https://news.google.com/?hl=en-IN&gl=IN&ceid=IN:en'
}

const topics = {
    entertainment: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pIUWlnQVAB',
    tech: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pIUWlnQVAB',
    business: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pIUWlnQVAB',
    world: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pIUWlnQVAB',
    sports: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZEdvU0FtVnVHZ0pIUWlnQVAB',
    science: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp0Y1RjU0FtVnVHZ0pIUWlnQVAB',
    health: 'CAAqIQgKIhtDQkFTRGdvSUwyMHZNR3QwTlRFU0FtVnVLQUFQAQ',
    country: 'CAAqIQgKIhtDQkFTRGdvSUwyMHZNRGR6YzJNU0FtVnVLQUFQAQ',
}

const sections = {
    economy: 'CAQiTENCQVNNd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1HZG1jSE16S2dzU0NTOXRMekJuWm5Cek15Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    markets: 'CAQiYENCQVNRZ29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1EbDVOSEJ0S2hvS0dBb1VUVUZTUzBWVVUxOVRSVU5VU1U5T1gwNUJUVVVnQVNnQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    jobs: 'CAQiXENCQVNQd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERjBjWEpyS2hjS0ZRb1JTazlDVTE5VFJVTlVTVTlPWDA1QlRVVWdBU2dBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlnQVABUAE',
    personal_finance: 'CAQiTENCQVNNd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERjVObU54S2dzU0NTOXRMekF4ZVRaamNTZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    entrepreneurship: 'CAQiSkNCQVNNUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESnVkM0VxQ2hJSUwyMHZNREp1ZDNFb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlnQVABUAE',
    gobile: 'CAQiZkNCQVNSZ29JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EVXdhemdxSHdvZENobE5UMEpKVEVWZlVFaFBUa1ZmVTBWRFZFbFBUbDlPUVUxRklBRW9BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRGRqTVhZU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    gadgets: 'CAQiX0NCQVNRUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ESnRaakZ1S2hrS0Z3b1RSMEZFUjBWVVgxTkZRMVJKVDA1ZlRrRk5SU0FCS0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    internet: 'CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ETnliSFFxQ2hJSUwyMHZNRE55YkhRb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    vr: 'CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGZibmtxQ2hJSUwyMHZNRGRmYm5rb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    ai: 'CAQiR0NCQVNMd29JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJTkNBUWFDUW9ITDIwdk1HMXJlaW9KRWdjdmJTOHdiV3Q2S0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    computing: 'CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERnNjSE1xQ2hJSUwyMHZNREZzY0hNb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    movies: 'CAQiXkNCQVNRQW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjJlRzRxR1FvWENoTk5UMVpKUlZOZlUwVkRWRWxQVGw5T1FVMUZJQUVvQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    music: 'CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EUnliR1lxQ2hJSUwyMHZNRFJ5YkdZb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    tv: 'CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGpOVElxQ2hJSUwyMHZNRGRqTlRJb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    books: 'CAQiXkNCQVNRQW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1HSjBYMk16S2hnS0Znb1NRazlQUzFOZlUwVkRWRWxQVGw5T1FVMUZJQUVvQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    art: 'CAQiR0NCQVNMd29JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJTkNBUWFDUW9ITDIwdk1HcHFkeW9KRWdjdmJTOHdhbXAzS0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    celebrities: 'CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERnlabm9xQ2hJSUwyMHZNREZ5Wm5vb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    cricket: 'CAQiTENCQVNNd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ESTBibW94S2dzS0NSSUhRM0pwWTJ0bGRDZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    hockey: 'CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUkNBUWFEUW9MTDIwdk1ERXhZbUk0TWpNcUNnb0lFZ1pJYjJOclpYa29BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    tennis: 'CAQiSkNCQVNNUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGljekFxQ2dvSUVnWlVaVzV1YVhNb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlnQVABUAE',
    football: 'CAQiTENCQVNNd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjJlRFFxREFvS0VnaEdiMjkwWW1Gc2JDZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    badminton: 'CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERTVOR1FxRFFvTEVnbENZV1J0YVc1MGIyNG9BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    kabbadi: 'CAQiS0NCQVNNZ29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EUmlNSE1xQ3dvSkVnZExZV0ppWVdScEtBQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    womens_cricket: 'CAQiV0NCQVNPd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1EY3diV3M0S2hNS0VSSVBWMjl0Wlc0bmN5QkRjbWxqYTJWMEtBQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    basketball: 'CAQiT0NCQVNOUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERTRkemdxRGdvTUVncENZWE5yWlhSaVlXeHNLQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    f1: 'CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjRlaklxRFFvTEVnbEdNU0JTWVdOcGJtY29BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    medicine: 'CAQiRENCQVNMUW9JTDIwdk1HdDBOVEVTQldWdUxVZENJZzRJQkJvS0NnZ3ZiUzh3TkhOb015b0tFZ2d2YlM4d05ITm9NeWdBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    healthcare: 'CAQiR0NCQVNMd29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TVcxM01uZ3FDeElKTDIwdk1ERnRkeko0S0FBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    mental_health: 'CAQiR0NCQVNMd29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TTNnMk9XY3FDeElKTDIwdk1ETjROamxuS0FBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    nutrition: 'CAQiRENCQVNMUW9JTDIwdk1HdDBOVEVTQldWdUxVZENJZzRJQkJvS0NnZ3ZiUzh3TldScVl5b0tFZ2d2YlM4d05XUnFZeWdBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    fitness: 'CAQiW0NCQVNQZ29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TWpkNE4yNHFHZ29ZQ2hSR1NWUk9SVk5UWDFORlExUkpUMDVmVGtGTlJTQUJLQUEqKQgAKiUICiIfQ0JBU0VRb0lMMjB2TUd0ME5URVNCV1Z1TFVkQ0tBQVABUAE',
    environment: 'CAQiT0NCQVNOUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUUNBUWFEQW9LTDIwdk1EUTJOak15Y3lvTUVnb3ZiUzh3TkRZMk16SnpLQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    outer_space: 'CAQiTENCQVNNd29JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERTRNek4zS2dzU0NTOXRMekF4T0RNemR5Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    physics: 'CAQiSkNCQVNNUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EVnhhblFxQ2hJSUwyMHZNRFZ4YW5Rb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlnQVABUAE',
    genetics: 'CAQiSkNCQVNNUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ETTJYeklxQ2hJSUwyMHZNRE0yWHpJb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlnQVABUAE',
    wildlife: 'CAQiTENCQVNNd29JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERXlPREJuS2dzU0NTOXRMekF4TWpnd1p5Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ'

}

country = {
af : 'af',
al : 'al',
dz : 'dz',
as : 'as',
ad : 'ad',
ao : 'ao',
ai : 'ai',
aq : 'aq',
ag : 'ag',
ar : 'ar',
am : 'am',
aw : 'aw',
au : 'au',
at : 'at',
az : 'az',
bs : 'bs',
bh : 'bh',
bd : 'bd',
bb : 'bb',
by : 'by',
be : 'be',
bz : 'bz',
bj : 'bj',
bm : 'bm',
bt : 'bt',
bo : 'bo',
ba : 'ba',
bw : 'bw',
bv : 'bv',
br : 'br',
io : 'io',
bn : 'bn',
bg : 'bg',
bf : 'bf',
bi : 'bi',
kh : 'kh',
cm : 'cm',
ca : 'ca',
cv : 'cv',
ky : 'ky',
cf : 'cf',
td : 'td',
cl : 'cl',
cn : 'cn',
cx : 'cx',
cc : 'cc',
co : 'co',
km : 'km',
cg : 'cg',
cd : 'cd',
ck : 'ck',
cr : 'cr',
ci : 'ci',
hr : 'hr',
cu : 'cu',
cy : 'cy',
cz : 'cz',
dk : 'dk',
dj : 'dj',
dm : 'dm',
do : 'do',
ec : 'ec',
eg : 'eg',
sv : 'sv',
gq : 'gq',
er : 'er',
ee : 'ee',
et : 'et',
fk : 'fk',
fo : 'fo',
fj : 'fj',
fi : 'fi',
fr : 'fr',
gf : 'gf',
pf : 'pf',
tf : 'tf',
ga : 'ga',
gm : 'gm',
ge : 'ge',
de : 'de',
gh : 'gh',
gi : 'gi',
gr : 'gr',
gl : 'gl',
gd : 'gd',
gp : 'gp',
gu : 'gu',
gt : 'gt',
gn : 'gn',
gw : 'gw',
gy : 'gy',
ht : 'ht',
hm : 'hm',
va : 'va',
hn : 'hn',
hk : 'hk',
hu : 'hu',
is : 'is',
in : 'in',
id : 'id',
ir : 'ir',
iq : 'iq',
ie : 'ie',
il : 'il',
it : 'it',
jm : 'jm',
jp : 'jp',
jo : 'jo',
kz : 'kz',
ke : 'ke',
ki : 'ki',
kp : 'kp',
kr : 'kr',
kw : 'kw',
kg : 'kg',
la : 'la',
lv : 'lv',
lb : 'lb',
ls : 'ls',
lr : 'lr',
ly : 'ly',
li : 'li',
lt : 'lt',
lu : 'lu',
mo : 'mo',
mk : 'mk',
mg : 'mg',
mw : 'mw',
my : 'my',
mv : 'mv',
ml : 'ml',
mt : 'mt',
mh : 'mh',
mq : 'mq',
mr : 'mr',
mu : 'mu',
yt : 'yt',
mx : 'mx',
fm : 'fm',
md : 'md',
mc : 'mc',
mn : 'mn',
ms : 'ms',
ma : 'ma',
mz : 'mz',
mm : 'mm',
na : 'na',
nr : 'nr',
np : 'np',
nl : 'nl',
an : 'an',
nc : 'nc',
nz : 'nz',
ni : 'ni',
ne : 'ne',
ng : 'ng',
nu : 'nu',
nf : 'nf',
mp : 'mp',
no : 'no',
om : 'om',
pk : 'pk',
pw : 'pw',
ps : 'ps',
pa : 'pa',
pg : 'pg',
py : 'py',
pe : 'pe',
ph : 'ph',
pn : 'pn',
pl : 'pl',
pt : 'pt',
pr : 'pr',
qa : 'qa',
re : 're',
ro : 'ro',
ru : 'ru',
rw : 'rw',
sh : 'sh',
kn : 'kn',
lc : 'lc',
pm : 'pm',
vc : 'vc',
ws : 'ws',
sm : 'sm',
st : 'st',
sa : 'sa',
sn : 'sn',
cs : 'cs',
sc : 'sc',
sl : 'sl',
sg : 'sg',
sk : 'sk',
si : 'si',
sb : 'sb',
so : 'so',
za : 'za',
gs : 'gs',
es : 'es',
lk : 'lk',
sd : 'sd',
sr : 'sr',
sj : 'sj',
sz : 'sz',
se : 'se',
ch : 'ch',
sy : 'sy',
tw : 'tw',
tj : 'tj',
tz : 'tz',
th : 'th',
tl : 'tl',
tg : 'tg',
tk : 'tk',
to : 'to',
tt : 'tt',
tn : 'tn',
tr : 'tr',
tm : 'tm',
tc : 'tc',
tv : 'tv',
ug : 'ug',
ua : 'ua',
ae : 'ae',
uk : 'uk',
us : 'us',
um : 'um',
uy : 'uy',
uz : 'uz',
vu : 'vu',
ve : 've',
vn : 'vn',
vg : 'vg',
vi : 'vi',
wf : 'wf',
eh : 'eh',
ye : 'ye',
zm : 'zm',
zw : 'zw'
}

lang = {
    af: 'af',
    sq: 'sq',
    sm: 'sm',
    ar: 'ar',
    az: 'az',
    eu: 'eu',
    be: 'be',
    bn: 'bn',
    bh: 'bh',
    bs: 'bs',
    bg: 'bg',
    ca: 'ca',
    zh_CN: 'zh-CN',
    zh_TW: 'zh-TW',
    hr: 'hr',
    cs: 'cs',
    da: 'da',
    nl: 'nl',
    en: 'en',
    eo: 'eo',
    et: 'et',
    fo: 'fo',
    fi: 'fi',
    fr: 'fr',
    fy: 'fy',
    gl: 'gl',
    ka: 'ka',
    de: 'de',
    el: 'el',
    gu: 'gu',
    iw: 'iw',
    hi: 'hi',
    hu: 'hu',
    is: 'is',
    id: 'id',
    ia: 'ia',
    ga: 'ga',
    it: 'it',
    ja: 'ja',
    jw: 'jw',
    kn: 'kn',
    ko: 'ko',
    la: 'la',
    lv: 'lv',
    lt: 'lt',
    mk: 'mk',
    ms: 'ms',
    ml: 'ml',
    mt: 'mt',
    mr: 'mr',
    ne: 'ne',
    no: 'no',
    nn: 'nn',
    oc: 'oc',
    fa: 'fa',
    pl: 'pl',
    pt_BR: 'pt-BR',
    pt_PT: 'pt-PT',
    pa: 'pa',
    ro: 'ro',
    ru: 'ru',
    gd: 'gd',
    sr: 'sr',
    si: 'si',
    sk: 'sk',
    sl: 'sl',
    es: 'es',
    su: 'su',
    sw: 'sw',
    sv: 'sv',
    tl: 'tl',
    ta: 'ta',
    te: 'te',
    th: 'th',
    ti: 'ti',
    tr: 'tr',
    uk: 'uk',
    ur: 'ur',
    uz: 'uz',
    vi: 'vi',
    cy: 'cy',
    xh: 'xh',
    zu: 'zu'
}


module.exports = { baseUrl, topics, sections, lang, country };