const baseUrl = {
    url: 'https://news.google.com/?hl=en-IN&gl=IN&ceid=IN:en'
}

const topics = {
    entertainment: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pIUWlnQVAB',
    tech: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pIUWlnQVAB',
    business: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pIUWlnQVAB',
    world: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pIUWlnQVAB',
    sports: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZEdvU0FtVnVHZ0pIUWlnQVAB',
    science: 'CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp0Y1RjU0FtVnVHZ0pIUWlnQVAB',
    health: 'CAAqIQgKIhtDQkFTRGdvSUwyMHZNR3QwTlRFU0FtVnVLQUFQAQ',
    country: 'CAAqIQgKIhtDQkFTRGdvSUwyMHZNRGR6YzJNU0FtVnVLQUFQAQ',
}

const sections = {
    economy: 'CAQiTENCQVNNd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1HZG1jSE16S2dzU0NTOXRMekJuWm5Cek15Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    markets: 'CAQiYENCQVNRZ29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1EbDVOSEJ0S2hvS0dBb1VUVUZTUzBWVVUxOVRSVU5VU1U5T1gwNUJUVVVnQVNnQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    jobs: 'CAQiXENCQVNQd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERjBjWEpyS2hjS0ZRb1JTazlDVTE5VFJVTlVTVTlPWDA1QlRVVWdBU2dBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlnQVABUAE',
    personal_finance: 'CAQiTENCQVNNd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERjVObU54S2dzU0NTOXRMekF4ZVRaamNTZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    entrepreneurship: 'CAQiSkNCQVNNUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESnVkM0VxQ2hJSUwyMHZNREp1ZDNFb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlnQVABUAE',
    gobile: 'CAQiZkNCQVNSZ29JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EVXdhemdxSHdvZENobE5UMEpKVEVWZlVFaFBUa1ZmVTBWRFZFbFBUbDlPUVUxRklBRW9BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRGRqTVhZU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    gadgets: 'CAQiX0NCQVNRUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ESnRaakZ1S2hrS0Z3b1RSMEZFUjBWVVgxTkZRMVJKVDA1ZlRrRk5SU0FCS0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    internet: 'CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ETnliSFFxQ2hJSUwyMHZNRE55YkhRb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    vr: 'CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGZibmtxQ2hJSUwyMHZNRGRmYm5rb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    ai: 'CAQiR0NCQVNMd29JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJTkNBUWFDUW9ITDIwdk1HMXJlaW9KRWdjdmJTOHdiV3Q2S0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    computing: 'CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERnNjSE1xQ2hJSUwyMHZNREZzY0hNb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE',
    movies: 'CAQiXkNCQVNRQW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjJlRzRxR1FvWENoTk5UMVpKUlZOZlUwVkRWRWxQVGw5T1FVMUZJQUVvQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    music: 'CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EUnliR1lxQ2hJSUwyMHZNRFJ5YkdZb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    tv: 'CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGpOVElxQ2hJSUwyMHZNRGRqTlRJb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    books: 'CAQiXkNCQVNRQW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1HSjBYMk16S2hnS0Znb1NRazlQUzFOZlUwVkRWRWxQVGw5T1FVMUZJQUVvQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    art: 'CAQiR0NCQVNMd29JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJTkNBUWFDUW9ITDIwdk1HcHFkeW9KRWdjdmJTOHdhbXAzS0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    celebrities: 'CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERnlabm9xQ2hJSUwyMHZNREZ5Wm5vb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE',
    cricket: 'CAQiTENCQVNNd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ESTBibW94S2dzS0NSSUhRM0pwWTJ0bGRDZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    hockey: 'CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUkNBUWFEUW9MTDIwdk1ERXhZbUk0TWpNcUNnb0lFZ1pJYjJOclpYa29BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    tennis: 'CAQiSkNCQVNNUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGljekFxQ2dvSUVnWlVaVzV1YVhNb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlnQVABUAE',
    football: 'CAQiTENCQVNNd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjJlRFFxREFvS0VnaEdiMjkwWW1Gc2JDZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    badminton: 'CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERTVOR1FxRFFvTEVnbENZV1J0YVc1MGIyNG9BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    kabbadi: 'CAQiS0NCQVNNZ29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EUmlNSE1xQ3dvSkVnZExZV0ppWVdScEtBQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    womens_cricket: 'CAQiV0NCQVNPd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1EY3diV3M0S2hNS0VSSVBWMjl0Wlc0bmN5QkRjbWxqYTJWMEtBQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    basketball: 'CAQiT0NCQVNOUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERTRkemdxRGdvTUVncENZWE5yWlhSaVlXeHNLQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    f1: 'CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjRlaklxRFFvTEVnbEdNU0JTWVdOcGJtY29BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB',
    medicine: 'CAQiRENCQVNMUW9JTDIwdk1HdDBOVEVTQldWdUxVZENJZzRJQkJvS0NnZ3ZiUzh3TkhOb015b0tFZ2d2YlM4d05ITm9NeWdBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    healthcare: 'CAQiR0NCQVNMd29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TVcxM01uZ3FDeElKTDIwdk1ERnRkeko0S0FBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    mental_health: 'CAQiR0NCQVNMd29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TTNnMk9XY3FDeElKTDIwdk1ETjROamxuS0FBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    nutrition: 'CAQiRENCQVNMUW9JTDIwdk1HdDBOVEVTQldWdUxVZENJZzRJQkJvS0NnZ3ZiUzh3TldScVl5b0tFZ2d2YlM4d05XUnFZeWdBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB',
    fitness: 'CAQiW0NCQVNQZ29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TWpkNE4yNHFHZ29ZQ2hSR1NWUk9SVk5UWDFORlExUkpUMDVmVGtGTlJTQUJLQUEqKQgAKiUICiIfQ0JBU0VRb0lMMjB2TUd0ME5URVNCV1Z1TFVkQ0tBQVABUAE',
    environment: 'CAQiT0NCQVNOUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUUNBUWFEQW9LTDIwdk1EUTJOak15Y3lvTUVnb3ZiUzh3TkRZMk16SnpLQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    outer_space: 'CAQiTENCQVNNd29JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERTRNek4zS2dzU0NTOXRMekF4T0RNemR5Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ',
    physics: 'CAQiSkNCQVNNUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EVnhhblFxQ2hJSUwyMHZNRFZ4YW5Rb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlnQVABUAE',
    genetics: 'CAQiSkNCQVNNUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ETTJYeklxQ2hJSUwyMHZNRE0yWHpJb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlnQVABUAE',
    wildlife: 'CAQiTENCQVNNd29JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERXlPREJuS2dzU0NTOXRMekF4TWpnd1p5Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ'

}

country = {
af : 'AF',
al : 'AL',
dz : 'DZ',
as : 'AS',
ad : 'AD',
ao : 'AO',
ai : 'AI',
aq : 'AQ',
ag : 'AG',
ar : 'AR',
am : 'AM',
aw : 'AW',
au : 'AU',
at : 'AT',
az : 'AZ',
bs : 'BS',
bh : 'BH',
bd : 'BD',
bb : 'BB',
by : 'BY',
be : 'BE',
bz : 'BZ',
bj : 'BJ',
bm : 'BM',
bt : 'BT',
bo : 'BO',
ba : 'BA',
bw : 'BW',
bv : 'BV',
br : 'BR',
io : 'IO',
bn : 'BN',
bg : 'BG',
bf : 'BF',
bi : 'BI',
kh : 'KH',
cm : 'CM',
ca : 'CA',
cv : 'CV',
ky : 'KY',
cf : 'CF',
td : 'TD',
cl : 'CL',
cn : 'CN',
cx : 'CX',
cc : 'CC',
co : 'CO',
km : 'KM',
cg : 'CG',
cd : 'CD',
ck : 'CK',
cr : 'CR',
ci : 'CI',
hr : 'HR',
cu : 'CU',
cy : 'CY',
cz : 'CZ',
dk : 'DK',
dj : 'DJ',
dm : 'DM',
do : 'DO',
ec : 'EC',
eg : 'EG',
sv : 'SV',
gq : 'GQ',
er : 'ER',
ee : 'EE',
et : 'ET',
fk : 'FK',
fo : 'FO',
fj : 'FJ',
fi : 'FI',
fr : 'FR',
gf : 'GF',
pf : 'PF',
tf : 'TF',
ga : 'GA',
gm : 'GM',
ge : 'GE',
de : 'DE',
gh : 'GH',
gi : 'GI',
gr : 'GR',
gl : 'GL',
gd : 'GD',
gp : 'GP',
gu : 'GU',
gt : 'GT',
gn : 'GN',
gw : 'GW',
gy : 'GY',
ht : 'HT',
hm : 'HM',
va : 'VA',
hn : 'HN',
hk : 'HK',
hu : 'HU',
is : 'IS',
in : 'IN',
id : 'ID',
ir : 'IR',
iq : 'IQ',
ie : 'IE',
il : 'IL',
it : 'IT',
jm : 'JM',
jp : 'JP',
jo : 'JO',
kz : 'KZ',
ke : 'KE',
ki : 'KI',
kp : 'KP',
kr : 'KR',
kw : 'KW',
kg : 'KG',
la : 'LA',
lv : 'LV',
lb : 'LB',
ls : 'LS',
lr : 'LR',
ly : 'LY',
li : 'LI',
lt : 'LT',
lu : 'LU',
mo : 'MO',
mk : 'MK',
mg : 'MG',
mw : 'MW',
my : 'MY',
mv : 'MV',
ml : 'ML',
mt : 'MT',
mh : 'MH',
mq : 'MQ',
mr : 'MR',
mu : 'MU',
yt : 'YT',
mx : 'MX',
fm : 'FM',
md : 'MD',
mc : 'MC',
mn : 'MN',
ms : 'MS',
ma : 'MA',
mz : 'MZ',
mm : 'MM',
na : 'NA',
nr : 'NR',
np : 'NP',
nl : 'NL',
an : 'AN',
nc : 'NC',
nz : 'NZ',
ni : 'NI',
ne : 'NE',
ng : 'NG',
nu : 'NU',
nf : 'NF',
mp : 'MP',
no : 'NO',
om : 'OM',
pk : 'PK',
pw : 'PW',
ps : 'PS',
pa : 'PA',
pg : 'PG',
py : 'PY',
pe : 'PE',
ph : 'PH',
pn : 'PN',
pl : 'PL',
pt : 'PT',
pr : 'PR',
qa : 'QA',
re : 'RE',
ro : 'RO',
ru : 'RU',
rw : 'RW',
sh : 'SH',
kn : 'KN',
lc : 'LC',
pm : 'PM',
vc : 'VC',
ws : 'WS',
sm : 'SM',
st : 'ST',
sa : 'SA',
sn : 'SN',
cs : 'CS',
sc : 'SC',
sl : 'SL',
sg : 'SG',
sk : 'SK',
si : 'SI',
sb : 'SB',
so : 'SO',
za : 'ZA',
gs : 'GS',
es : 'ES',
lk : 'LK',
sd : 'SD',
sr : 'SR',
sj : 'SJ',
sz : 'SZ',
se : 'SE',
ch : 'CH',
sy : 'SY',
tw : 'TW',
tj : 'TJ',
tz : 'TZ',
th : 'TH',
tl : 'TL',
tg : 'TG',
tk : 'TK',
to : 'TO',
tt : 'TT',
tn : 'TN',
tr : 'TR',
tm : 'TM',
tc : 'TC',
tv : 'TV',
ug : 'UG',
ua : 'UA',
ae : 'AE',
uk : 'GB',
us : 'US',
um : 'UM',
uy : 'UY',
uz : 'UZ',
vu : 'VU',
ve : 'VE',
vn : 'VN',
vg : 'VG',
vi : 'VI',
wf : 'WF',
eh : 'EH',
ye : 'YE',
zm : 'ZM',
zw : 'ZW'
}

lang = {
    af: 'af',
    sq: 'sq',
    sm: 'sm',
    ar: 'ar',
    az: 'az',
    eu: 'eu',
    be: 'be',
    bn: 'bn',
    bh: 'bh',
    bs: 'bs',
    bg: 'bg',
    ca: 'ca',
    'zh-CN': 'zh-CN',
    'zh-TW': 'zh-TW',
    hr: 'hr',
    cs: 'cs',
    da: 'da',
    nl: 'nl',
    en: 'en',
    eo: 'eo',
    et: 'et',
    fo: 'fo',
    fi: 'fi',
    fr: 'fr',
    fy: 'fy',
    gl: 'gl',
    ka: 'ka',
    de: 'de',
    el: 'el',
    gu: 'gu',
    iw: 'iw',
    hi: 'hi',
    hu: 'hu',
    is: 'is',
    id: 'id',
    ia: 'ia',
    ga: 'ga',
    it: 'it',
    ja: 'ja',
    jw: 'jw',
    kn: 'kn',
    ko: 'ko',
    la: 'la',
    lv: 'lv',
    lt: 'lt',
    mk: 'mk',
    ms: 'ms',
    ml: 'ml',
    mt: 'mt',
    mr: 'mr',
    ne: 'ne',
    no: 'no',
    nn: 'nn',
    oc: 'oc',
    fa: 'fa',
    pl: 'pl',
    'pt-BR': 'pt-BR',
    'pt-PT': 'pt-PT',
    pa: 'pa',
    ro: 'ro',
    ru: 'ru',
    gd: 'gd',
    sr: 'sr',
    si: 'si',
    sk: 'sk',
    sl: 'sl',
    es: 'es',
    su: 'su',
    sw: 'sw',
    sv: 'sv',
    tl: 'tl',
    ta: 'ta',
    te: 'te',
    th: 'th',
    ti: 'ti',
    tr: 'tr',
    uk: 'uk',
    ur: 'ur',
    uz: 'uz',
    vi: 'vi',
    cy: 'cy',
    xh: 'xh',
    zu: 'zu'
}


module.exports = { baseUrl, topics, sections, lang, country };