
{
    entertainment: "CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pIUWlnQVAB"
    tech : "CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pIUWlnQVAB"
    business: "CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pIUWlnQVAB"
    world : "CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pIUWlnQVAB"
    sports : "CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZEdvU0FtVnVHZ0pIUWlnQVAB"
    science: "CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp0Y1RjU0FtVnVHZ0pIUWlnQVAB"
    health : "CAAqIQgKIhtDQkFTRGdvSUwyMHZNR3QwTlRFU0FtVnVLQUFQAQ"
    country : "CAAqIQgKIhtDQkFTRGdvSUwyMHZNRGR6YzJNU0FtVnVLQUFQAQ"
}

https://news.google.com/?hl=en-GB&gl=GB&ceid=GB%3Aen
https://news.google.com/topics/{TOPIC}?hl=en-GB&gl=GB&ceid=GB%3Aen
https://news.google.com/search?q=apple&hl=en-IN&gl=IN&ceid=IN:en
https://news.google.com/topics/{TOPIC}/sections/{Section}?hl=en-IN&gl=IN&ceid=IN%3Aen


a = document.querySelector('.xrnccd.F6Welf.R7GTQ')
link : a.querySelector('article').getAttribute('jslog').match(/\bhttps?:\/\/\S+/gi);
image : a.querySelector('img').getAttribute('src')
title : a.querySelector('.ipQwMb.ekueJc.RD0gLb').textContent
source : a.querySelector('.wEwyrc.AVN2gc.uQIVzc').textContent
time : a.querySelector('time').getAttribute('datetime')

// Related 
b = a.querySelector('.SbNwzf').querySelector('article')
title : b.querySelector('.ipQwMb.ekueJc.RD0gLb').innerText
link : b.querySelector('.ipQwMb.ekueJc.RD0gLb').querySelector('a').getAttribute('href').replace('./','https://news.google.com/')
source  : b.querySelector('.SVJrMe').querySelector('.wEwyrc.AVN2gc.uQIVzc').textContent
time : b.querySelector('time').getAttribute('datetime')


Latest : CAQqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAE
Economy : CAQiTENCQVNNd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1HZG1jSE16S2dzU0NTOXRMekJuWm5Cek15Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Markets : CAQiYENCQVNRZ29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1EbDVOSEJ0S2hvS0dBb1VUVUZTUzBWVVUxOVRSVU5VU1U5T1gwNUJUVVVnQVNnQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKSlRpZ0FQAVAB
Jobs : CAQiXENCQVNQd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERjBjWEpyS2hjS0ZRb1JTazlDVTE5VFJVTlVTVTlPWDA1QlRVVWdBU2dBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlnQVABUAE
Personal_finance : CAQiTENCQVNNd29JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERjVObU54S2dzU0NTOXRMekF4ZVRaamNTZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURsek1XWVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Entrepreneurship : CAQiSkNCQVNNUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESnVkM0VxQ2hJSUwyMHZNREp1ZDNFb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EbHpNV1lTQldWdUxVZENHZ0pKVGlnQVABUAE


Latest : CAQqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURkak1YWVNCV1Z1TFVkQ0dnSkpUaWdBUAE
Mobile : CAQiZkNCQVNSZ29JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EVXdhemdxSHdvZENobE5UMEpKVEVWZlVFaFBUa1ZmVTBWRFZFbFBUbDlPUVUxRklBRW9BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRGRqTVhZU0JXVnVMVWRDR2dKSlRpZ0FQAVAB
Gadgets : CAQiX0NCQVNRUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ESnRaakZ1S2hrS0Z3b1RSMEZFUjBWVVgxTkZRMVJKVDA1ZlRrRk5SU0FCS0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE
Internet : CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ETnliSFFxQ2hJSUwyMHZNRE55YkhRb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE
Virtual_reality : CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGZibmtxQ2hJSUwyMHZNRGRmYm5rb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE
Artificial_intelligence : CAQiR0NCQVNMd29JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJTkNBUWFDUW9ITDIwdk1HMXJlaW9KRWdjdmJTOHdiV3Q2S0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE
Computing : CAQiSkNCQVNNUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERnNjSE1xQ2hJSUwyMHZNREZzY0hNb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EZGpNWFlTQldWdUxVZENHZ0pKVGlnQVABUAE


Latest : CAQqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAE
Movies : CAQiXkNCQVNRQW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjJlRzRxR1FvWENoTk5UMVpKUlZOZlUwVkRWRWxQVGw5T1FVMUZJQUVvQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Music : CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EUnliR1lxQ2hJSUwyMHZNRFJ5YkdZb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE
TV : CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGpOVElxQ2hJSUwyMHZNRGRqTlRJb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE
Books : CAQiXkNCQVNRQW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1HSjBYMk16S2hnS0Znb1NRazlQUzFOZlUwVkRWRWxQVGw5T1FVMUZJQUVvQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURKcWFuUVNCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Art : CAQiR0NCQVNMd29JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJTkNBUWFDUW9ITDIwdk1HcHFkeW9KRWdjdmJTOHdhbXAzS0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE
Celebrities : CAQiSkNCQVNNUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERnlabm9xQ2hJSUwyMHZNREZ5Wm5vb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1ESnFhblFTQldWdUxVZENHZ0pKVGlnQVABUAE


Latest : CAQqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAE
Cricket : CAQiTENCQVNNd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ESTBibW94S2dzS0NSSUhRM0pwWTJ0bGRDZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Hockey : CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUkNBUWFEUW9MTDIwdk1ERXhZbUk0TWpNcUNnb0lFZ1pJYjJOclpYa29BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB
Tennis : CAQiSkNCQVNNUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EZGljekFxQ2dvSUVnWlVaVzV1YVhNb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlnQVABUAE
Football : CAQiTENCQVNNd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjJlRFFxREFvS0VnaEdiMjkwWW1Gc2JDZ0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Badminton : CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERTVOR1FxRFFvTEVnbENZV1J0YVc1MGIyNG9BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB
Kabbadi : CAQiS0NCQVNNZ29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EUmlNSE1xQ3dvSkVnZExZV0ppWVdScEtBQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB
Womens_Cricket : CAQiV0NCQVNPd29JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1EY3diV3M0S2hNS0VSSVBWMjl0Wlc0bmN5QkRjbWxqYTJWMEtBQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB
Basketball : CAQiT0NCQVNOUW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ERTRkemdxRGdvTUVncENZWE5yWlhSaVlXeHNLQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadWRHb1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
F1_Racing : CAQiTkNCQVNOQW9JTDIwdk1EWnVkR29TQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ESjRlaklxRFFvTEVnbEdNU0JTWVdOcGJtY29BQSouCAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKSlRpZ0FQAVAB


Latest : CAQqKQgAKiUICiIfQ0JBU0VRb0lMMjB2TUd0ME5URVNCV1Z1TFVkQ0tBQVAB
Medicine : CAQiRENCQVNMUW9JTDIwdk1HdDBOVEVTQldWdUxVZENJZzRJQkJvS0NnZ3ZiUzh3TkhOb015b0tFZ2d2YlM4d05ITm9NeWdBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB
Healthcare : CAQiR0NCQVNMd29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TVcxM01uZ3FDeElKTDIwdk1ERnRkeko0S0FBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB
Mental_health : CAQiR0NCQVNMd29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TTNnMk9XY3FDeElKTDIwdk1ETjROamxuS0FBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB
Nutrition : CAQiRENCQVNMUW9JTDIwdk1HdDBOVEVTQldWdUxVZENJZzRJQkJvS0NnZ3ZiUzh3TldScVl5b0tFZ2d2YlM4d05XUnFZeWdBKikIAColCAoiH0NCQVNFUW9JTDIwdk1HdDBOVEVTQldWdUxVZENLQUFQAVAB
Fitness : CAQiW0NCQVNQZ29JTDIwdk1HdDBOVEVTQldWdUxVZENJZzhJQkJvTENna3ZiUzh3TWpkNE4yNHFHZ29ZQ2hSR1NWUk9SVk5UWDFORlExUkpUMDVmVGtGTlJTQUJLQUEqKQgAKiUICiIfQ0JBU0VRb0lMMjB2TUd0ME5URVNCV1Z1TFVkQ0tBQVABUAE


Latest : CAQqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAE
Environment : CAQiT0NCQVNOUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUUNBUWFEQW9LTDIwdk1EUTJOak15Y3lvTUVnb3ZiUzh3TkRZMk16SnpLQUEqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Outer_space : CAQiTENCQVNNd29JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERTRNek4zS2dzU0NTOXRMekF4T0RNemR5Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ
Physics : CAQiSkNCQVNNUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1EVnhhblFxQ2hJSUwyMHZNRFZ4YW5Rb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlnQVABUAE
Genetics : CAQiSkNCQVNNUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJT0NBUWFDZ29JTDIwdk1ETTJYeklxQ2hJSUwyMHZNRE0yWHpJb0FBKi4IACoqCAoiJENCQVNGUW9JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlnQVABUAE
Wildlife : CAQiTENCQVNNd29JTDIwdk1EWnRjVGNTQldWdUxVZENHZ0pKVGlJUENBUWFDd29KTDIwdk1ERXlPREJuS2dzU0NTOXRMekF4TWpnd1p5Z0EqLggAKioICiIkQ0JBU0ZRb0lMMjB2TURadGNUY1NCV1Z1TFVkQ0dnSkpUaWdBUAFQAQ


{
   af : 'af',
   sq : 'sq',
   sm : 'sm',
   ar : 'ar',
   az : 'az',
   eu : 'eu',
   be : 'be',
   bn : 'bn',
   bh : 'bh',
   bs : 'bs',
   bg : 'bg',
   ca : 'ca',
   zh_CN : 'zh-CN',
   zh_TW : 'zh-TW',
   hr : 'hr',
   cs : 'cs',
   da : 'da',
   nl : 'nl',
   en : 'en',
   eo : 'eo',
   et : 'et',
   fo : 'fo',
   fi : 'fi',
   fr : 'fr',
   fy : 'fy',
   gl : 'gl',
   ka : 'ka',
   de : 'de',
   el : 'el',
   gu : 'gu',
   iw : 'iw',
   hi : 'hi',
   hu : 'hu',
   is : 'is',
   id : 'id',
   ia : 'ia',
   ga : 'ga',
   it : 'it',
   ja : 'ja',
   jw : 'jw',
   kn : 'kn',
   ko : 'ko',
   la : 'la',
   lv : 'lv',
   lt : 'lt',
   mk : 'mk',
   ms : 'ms',
   ml : 'ml',
   mt : 'mt',
   mr : 'mr',
   ne : 'ne',
   no : 'no',
   nn : 'nn',
   oc : 'oc',
   fa : 'fa',
   pl : 'pl',
   pt_BR : 'pt-BR',
   pt_PT : 'pt-PT',
   pa : 'pa',
   ro : 'ro',
   ru : 'ru',
   gd : 'gd',
   sr : 'sr',
   si : 'si',
   sk : 'sk',
   sl : 'sl',
   es : 'es',
   su : 'su',
   sw : 'sw',
   sv : 'sv',
   tl : 'tl',
   ta : 'ta',
   te : 'te',
   th : 'th',
   ti : 'ti',
   tr : 'tr',
   uk : 'uk',
   ur : 'ur',
   uz : 'uz',
   vi : 'vi',
   cy : 'cy',
   xh : 'xh',
   zu : 'zu'
}